<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CleanCinemaReservation.Core\CleanCinemaReservation.Core.csproj" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="2.29.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>